# Generated by Django 4.2.5 on 2023-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default='kjnfdknknfk'),
            preserve_default=False,
        ),
    ]
